#!/usr/bin/env bash
# Validate the deployment layer without starting the stack:
#   - every compose file renders (`docker compose config`)
#   - every edge proxy passes `nginx -t` inside its real compose definition
#     (same mounts, read-only paths, dropped capabilities) with real PKI
#     material from deploy/pki/out (generated by deploy/pki.sh if missing).
#
# Used by CI and safe on an operator machine: it runs under its own compose
# project name, never touches running containers, and removes the placeholder
# files it creates.
set -euo pipefail
cd "$(dirname "$0")/.."

PROJECT="argus-deploy-check"
created=()
override="$(mktemp)"

cleanup() {
  for f in "${created[@]}"; do rm -f "$f"; done
  rm -f "$override"
}
trap cleanup EXIT

# Placeholders only so the `${VAR:?}` guards pass; no stack is started.
export POSTGRES_PASSWORD=check PARKING_POSTGRES_PASSWORD=check \
  MEDIAMTX_API_PASSWORD=check MEDIAMTX_PUBLISH_PASSWORD=check MEDIAMTX_READ_PASSWORD=check \
  PARKING_EDGE=parking-edge:8443 SURVEILLANCE_EDGE=surveillance-edge:8443

for f in services/surveillance/.env services/parking/.env; do
  if [[ ! -e "$f" ]]; then
    : >"$f"
    created+=("$f")
  fi
done

if [[ ! -f deploy/pki/out/ca.pem ]]; then
  deploy/pki.sh init
fi

# nginx resolves upstream hosts at startup; point them at loopback so the
# config can be tested without the upstream containers running.
write_override() {
  local edge="$1" host
  {
    printf 'services:\n  %s:\n    extra_hosts:\n' "$edge"
    for host in surveillance parking frontend mediamtx parking-mediamtx edge parking-edge; do
      printf '      - "%s:127.0.0.1"\n' "$host"
    done
  } >"$override"
}

check() {
  local file="$1" edge="$2"
  echo "==> $file"
  docker compose -p "$PROJECT" -f "$file" config -q
  write_override "$edge"
  docker compose -p "$PROJECT" -f "$file" -f "$override" run --rm --no-deps -T "$edge" nginx -t
  docker compose -p "$PROJECT" -f "$file" down --volumes --remove-orphans >/dev/null 2>&1 || true
}

check docker-compose.yml edge
check deploy/compose/docker-compose.surveillance.yml edge
check deploy/compose/docker-compose.parking.yml parking-edge
echo "deployment config OK"
